### ISSUE TITLE
Navbar flashes when clicking links

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/owd-website#2]
![owd-nav](https://user-images.githubusercontent.com/432915/185806106-048b9fdf-e0ff-497d-a580-174731f6c565.gif)

Related I guess to theme selection and the need to add the button in JS. Would be fixed by https://github.com/openwebdocs/owd-website/issues/1.

**Comment by queengooborg** [comment]
Can confirm; there's a slight delay since it's adding the new element.  Alternatively, we could turn it into a toggle switch or drop down menu?

**Comment by wbamberg** [comment]
Or move it into the footer , as Dom suggested in https://github.com/openwebdocs/website-old/issues/19#issuecomment-1090379710 . I would prefer #1 though, and most of all the only-have-dark-theme version of #1.
