### ISSUE TITLE
Sharing icon for the https://openwebdocs.org/ URL

### ISSUE THREAD

**Issue by robnyman** [openwebdocs/owd-website#25]
When sharing [https://openwebdocs.org/](https://openwebdocs.org/) through different tools right now, it picks the Edge logo as the first image. I guess that's because the logo is a SVG file and the Edge logo is the first PNG file in the page. 

Also, right now the `<meta>` tags are empty:

```
<meta property="og:title" content="" />
<meta property="og:type" content="" />
<meta property="og:url" content="" />
<meta property="og:image" content="" />
```

Where it should be:

```
<meta property="og:title" content="your_link_title">
<meta property="og:image" content="your_image_url">
```

And so on.

**Comment by Elchi3** [comment]
@robnyman can you test again if this works now? We made some changes to the OG meta tags and the main logo is now PNG.

**Comment by robnyman** [comment]
I tried both the deploy URL at https://deploy-preview-26--beautiful-dieffenbachia-e315ce.netlify.app/, and https://openwebdocs.org/. 

- For Twitter, deploy rendered a broken image and real URL didn't generate anything. 
- Both worked on Facebook with the logo image chosen, not the favicon. 
- Google Chat still chose the Canva logo, for whatever reason… 
- Slack chooses the favicon.

I believe it perhaps needs to be absolute URLs, at least for the meta tags. I.e:

<meta property="og:title" content="Open Web Docs" />
<meta property="og:image" content="https://openwebdocs.org/img/openwebdocs-logo.png" />

But I'm just speculating…

**Comment by Elchi3** [comment]
okay, made another fix and https://cards-dev.twitter.com/validator is green now. I see it working on twitter now, too.

**Comment by Elchi3** [comment]
I think it was due to an empty meta description tag

**Comment by robnyman** [comment]
Ok! Is this meant to be on openwebdocs.org now? I tried a new tweet with it and got a broken image. and when I looked at the source I couldn't see any Twitter-specific tags.

**Comment by Elchi3** [comment]
Yes, so I guess by broken image you mean that there should be a dedicated square twitter image?

![Bildschirmfoto 2022-09-13 um 18 26 56](https://user-images.githubusercontent.com/349114/189955933-57315725-d9e6-4fdb-b1b1-f1f5c5eb1b83.png)

I can try to add twitter meta tags and use a square logo. I guess that would be this: 
![](https://openwebdocs.org/favicon/android-icon-192x192.png)

**Comment by robnyman** [comment]
No, it was completely broken, as in broken image link.
But, now it works!! SO yay. :-)

**Comment by Elchi3** [comment]
Nice. I'm closing this then. Feel free to open new issues if there are more problems with sharing.
