### ISSUE TITLE
Add link to sponsors page

### ISSUE THREAD

**Issue by robnyman** [openwebdocs/owd-website#29]
The word/title Sponsors on the start page should link to [openwebdocs.org/sponsors](openwebdocs.org/sponsors).

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue! Does it have to open on the same page or open a new tab?

**Comment by robnyman** [comment]
I think it should be in the same page, just like the other links on the page.

**Comment by abitsalihu** [comment]
Okay, please assign this to me, also by adding a link to the header, the header will take the links "<a>" normal styling, should I implement the styling of it back to what it was before it was a link in the css?

**Comment by robnyman** [comment]
> Okay, please assign this to me, also by adding a link to the header, the header will take the links "" normal styling, should I implement the styling of it back to what it was before it was a link in the css?

Please keep the styling/look it already has as a header, and make it into a link. (probably best added with an id-specific style or similar in the CSS file). Thanks!

**Comment by Elchi3** [comment]
Fixed in https://github.com/openwebdocs/owd-website/pull/30
