### ISSUE TITLE
Meta logo is huge in "Sponsors" page

### ISSUE THREAD

**Issue by wbamberg** [openwebdocs/owd-website#51]
As a side effect of https://github.com/openwebdocs/owd-website/pull/47 I think, the Meta logo is now huge in https://openwebdocs.org/sponsors/.

**Comment by queengooborg** [comment]
Is there a particular reason that we're including the name in the logo as well?  If we crop the image to remove the word "Meta", that should greatly help us ensure consistent sizing of all sponsor logos.
