### ISSUE TITLE
Add RSS to the blog

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/owd-website#54]
Maybe I'm old but I think the blog should have RSS. Seems like there is an 11ty plugin.

https://github.com/openwebdocs/owd-website/blob/bc05579783c107d29b0c8c9293b2bc3165143e4c/.eleventy.js#L47

**Comment by dontcallmedom** [comment]
see also https://twitter.com/simevidas/status/1579920290078896128 :)
