### ISSUE TITLE
Layout Shift in Safari

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/owd-website#87]
The site jumps when I navigate in Safari. Maybe it has to do with the main OWD logo image? Looks stable in Chrome.

**Comment by Elchi3** [comment]
https://github.com/openwebdocs/owd-website/assets/349114/f123c1d9-987c-4bff-a890-d781533f742f

**Comment by estelle** [comment]
I am unable to replicate on my safari. Are you on localhost or netlify URL  or the live site?

**Comment by Elchi3** [comment]
This was the live site in a private window. If no one else can produce this, then I'm happy to not mind. Maybe it is a content blocker, or some other thing in my Safari.
